default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  primary:
    <<: *default
    database: topsekrit_development
  queue:
    <<: *default
    database: topsekrit_development_queue
    migrations_paths: db/queue_migrate
test:
  <<: *default
  database: topsekrit_test
