# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c68245304f7e10258f8fdb82567a543b54d9ed7820dae5638f424874fd210da985f847d37f4dd501910f98ca485e3c6485a8bd0493c066c3bf1915cf57728a0

test:
  secret_key_base: 0e375c465fc21abd24f58bdc4187da450c25fc2c92dbcfc828ddd7f7a1dfeadf98ef25d2bfa6ab96ecc042abccd78c42157bad96bb6e652c458f11de732a3035

staging:
  secret_key_base: <%= ENV["RAILS_SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["RAILS_SECRET_KEY_BASE"] %>
